# Wheels Development Environment
# Usage: docker compose -f compose.development.yml up -d

networks:
  cfwheels-network:
    driver: bridge

services:
  lucee6:
    build:
      context: ./
      dockerfile: ./tools/docker/lucee@6/Dockerfile
    image: cfwheels-dev-lucee6:latest
    ports:
      - "60006:60006"
    volumes:
      # Mount template as the application root
      - ./templates/default:/wheelsapp
      # Mount core framework to vendor location
      - ./core/src/wheels:/wheelsapp/vendor/wheels
      # Mount dependencies
      - ./vendor/wirebox:/wheelsapp/vendor/wirebox
      - ./vendor/testbox:/wheelsapp/vendor/testbox
      # Mount core tests for separate test runner
      - ./core/tests:/wheelsapp/core-tests
      # Mount CFConfig file
      - ./tools/docker/lucee@6/CFConfig.json:/wheelsapp/CFConfig.json
    networks:
      - cfwheels-network
    environment:
      - ENGINE_PORT=60006
      - ENGINE_VERSION=lucee@6
      - DEFAULT_DB=h2
      - WHEELS_ENV=development
      - BOX_SERVER_WEB_WEBROOT=/wheelsapp/public
      - BOX_SERVER_CFCONFIGFILE=/wheelsapp/CFConfig.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:60006/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s