# Minimal Wheels Docker Setup for Quick Testing
# Usage: docker compose -f compose.minimal.yml up -d
# This runs only Lucee 6 with H2 database (no external DB needed)

networks:
  cfwheels-network:
    driver: bridge

services:
  lucee6:
    build:
      context: ./
      dockerfile: ./tools/docker/lucee@6/Dockerfile
    image: cfwheels-test-lucee6:v1.0.2
    ports:
      - "60006:60006"
    volumes:
      - ./:/cfwheels-test-suite
    networks:
      - cfwheels-network
    environment:
      - ENGINE_PORT=60006
      - ENGINE_VERSION=lucee@6
      - DEFAULT_DB=h2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:60006/wheels/testbox/runner.cfm?db=h2"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s