# Wheels Core Framework Test Suite
# Usage: docker compose -f compose.core-tests.yml up -d

networks:
  cfwheels-network:
    driver: bridge

services:
  lucee6:
    build:
      context: ./
      dockerfile: ./tools/docker/lucee@6/Dockerfile
    image: cfwheels-test-lucee6:v1.0.2
    ports:
      - "60006:60006"
    volumes:
      # Mount entire project to container
      - ./:/wheelsapp
    networks:
      - cfwheels-network
    environment:
      - ENGINE_PORT=60006
      - ENGINE_VERSION=lucee@6
      - DEFAULT_DB=h2
      - WHEELS_ENV=testing
      - BOX_SERVER_WEB_WEBROOT=/wheelsapp/core/tests
      - BOX_SERVER_CFCONFIGFILE=/wheelsapp/tools/docker/lucee@6/CFConfig.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:60006/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s