<cfsetting requestTimeOut="300">
<!--- get the version of the database we're running against --->
<cftry>
	<cfdbinfo name="local.dbinfo" datasource="#application.wheels.dataSourceName#" type="version">
	<cfcatch type="any">
		<cfthrow
			message="Datasource not found?"
			detail="The CFDBINFO call appears to have failed when looking for #application.wheels.dataSourceName#"
		>
	</cfcatch>
</cftry>
<cfset local.db = LCase(
	Replace(
		local.dbinfo.database_productname,
		" ",
		"",
		"all"
	)
)>
<cfset local.dbMajorVersion = Val(ListFirst(local.dbinfo.database_version, "."))>

<!--- handle differences in database for identity inserts, column types etc --->
<cfset local.storageEngine = "">
<cfset local.dateTimeColumnType = "datetime">
<cfset local.textColumnType = "text">
<cfset local.intColumnType = "int">
<cfset local.floatColumnType = "float">
<cfset local.identityColumnType = "int NOT NULL IDENTITY(1,1)">

<cfif local.db IS "microsoftsqlserver">
	<cfset local.identityColumnType = "int NOT NULL IDENTITY(1,1)">
<cfelseif local.db IS "mysql" or local.db IS "mariadb">
	<cfset local.identityColumnType = "int NOT NULL AUTO_INCREMENT">
	<cfset local.storageEngine = "ENGINE=InnoDB">
<cfelseif local.db IS "h2">
	<cfset local.dbVersion = listToArray(local.dbInfo["DATABASE_VERSION"], " ")[1]>
	<cfif local.dbVersion eq '2.1.214'>
		<cfset local.identityColumnType = "INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY">
	<cfelseif local.dbVersion eq '1.3.172'>
		<cfset local.identityColumnType = "int NOT NULL IDENTITY">
	</cfif>
<cfelseif local.db IS "postgresql">
	<cfset local.identityColumnType = "SERIAL NOT NULL">
	<cfset local.dateTimeColumnType = "timestamp">
<cfelseif local.db IS "cockroachdb">
	<cfset local.identityColumnType = "SERIAL NOT NULL">
	<cfset local.dateTimeColumnType = "timestamp">
<cfelseif local.db IS "oracle">
	<cfset local.identityColumnType = "INTEGER GENERATED BY DEFAULT AS IDENTITY">
	<cfset local.dateTimeColumnType = "TIMESTAMP">
	<cfset local.intColumnType = "NUMBER(10)">
	<cfset local.textColumnType = "VARCHAR2(255)">
<cfelseif local.db IS "sqlite">
	<cfset local.identityColumnType = "INTEGER">
	<cfset local.dateTimeColumnType = "TEXT">
	<cfset local.textColumnType = "TEXT">
	<cfset local.intColumnType = "INTEGER">
	<cfset local.floatColumnType = "REAL">
</cfif>

<!--- Drop existing tables --->
<cftry>
	<cfquery datasource="#application.wheels.dataSourceName#">DROP TABLE<cfif local.db IS NOT "oracle" OR (local.db IS "oracle" AND local.dbMajorVersion GTE 23)> IF EXISTS</cfif> c_o_r_e_posts</cfquery>
	<cfcatch></cfcatch>
</cftry>
<cftry>
	<cfquery datasource="#application.wheels.dataSourceName#">DROP TABLE<cfif local.db IS NOT "oracle" OR (local.db IS "oracle" AND local.dbMajorVersion GTE 23)> IF EXISTS</cfif> c_o_r_e_authors</cfquery>
	<cfcatch></cfcatch>
</cftry>

<!--- Create tables --->
<cfquery datasource="#application.wheels.dataSourceName#">
CREATE TABLE c_o_r_e_authors (
	id #local.identityColumnType#,
	firstname varchar(100) NOT NULL,
	lastname varchar(100) NOT NULL,
	PRIMARY KEY(id)
) #local.storageEngine#
</cfquery>

<cfquery datasource="#application.wheels.dataSourceName#">
CREATE TABLE c_o_r_e_posts (
	id #local.identityColumnType#,
	authorid #local.intColumnType# NULL,
	title varchar(250) NOT NULL,
	body #local.textColumnType# NOT NULL,
	createdat #local.dateTimeColumnType# NOT NULL,
	updatedat #local.dateTimeColumnType# NOT NULL,
	deletedat #local.dateTimeColumnType# NULL,
	views #local.intColumnType# DEFAULT 0 NOT NULL,
	averagerating #local.floatColumnType# NULL,
	status varchar(20) DEFAULT 'draft' NOT NULL,
	PRIMARY KEY(id)
) #local.storageEngine#
</cfquery>

<!--- Populate data --->
<cfscript>
application.wo.model("author").create(firstName = "Per", lastName = "Djurner");
application.wo.model("author").create(firstName = "Tony", lastName = "Petruzzi");
application.wo.model("author").create(firstName = "Chris", lastName = "Peters");
application.wo.model("author").create(firstName = "Peter", lastName = "Amiri");
application.wo.model("author").create(firstName = "James", lastName = "Gibson");
application.wo.model("author").create(firstName = "Raul", lastName = "Riera");
application.wo.model("author").create(firstName = "Andy", lastName = "Bellenie");
application.wo.model("author").create(firstName = "Adam", lastName = "Chapman");
application.wo.model("author").create(firstName = "Tom", lastName = "King");
application.wo.model("author").create(firstName = "David", lastName = "Belanger");

// Seed a handful of posts for scaffold/generator examples.
local.per = application.wo.model("author").findOne(where = "firstName = 'Per'");
local.per.createPost(title = "First post", body = "Body 1", views = 5);
local.per.createPost(title = "Second post", body = "Body 2", views = 5);
local.per.createPost(title = "Third post", body = "Body 3", views = 0, averageRating = "3.2");

local.tony = application.wo.model("author").findOne(where = "firstName = 'Tony'");
local.tony.createPost(title = "Fourth post", body = "Body 4", views = 3, averageRating = "3.6");
local.tony.createPost(title = "Fifth post", body = "Body 5", views = 2, averageRating = "3.6");
</cfscript>
