/**
 * {{ModelName}} Model
 * Generated by Wheels Model Generator
 */
component extends="Model" {

    function config() {
        // Table configuration (optional)
        // table(name="{{tableName}}");

        // Associations
        {{#associations}}
        {{associationType}}(name="{{name}}"{{#dependent}}, dependent="{{dependent}}"{{/dependent}});
        {{/associations}}

        // Validations
        {{#validations}}
        {{validationType}}({{#properties}}property="{{properties}}"{{/properties}}{{#options}}, {{options}}{{/options}});
        {{/validations}}

        // Callbacks
        {{#callbacks}}
        {{callbackType}}("{{methodName}}");
        {{/callbacks}}
    }

    {{#customMethods}}
    // Custom methods
    public {{returnType}} function {{methodName}}({{#params}}{{paramType}} {{paramName}}{{^last}}, {{/last}}{{/params}}) {
        {{methodBody}}
    }
    {{/customMethods}}

    {{#callbackMethods}}
    // Callback methods
    private void function {{methodName}}() {
        {{methodBody}}
    }
    {{/callbackMethods}}
}
