/**
 * `wheels generate api-resource` adds its route to config/routes.cfm through
 * Scaffold.updateApiRoutes(). It joined the first `.namespace("api")` it
 * found, even one inside `wheels generate auth`'s marked block, which that
 * generator rewrites on --force (dropping the route); and it wrote the new
 * line just before `.end()` on the same line, pushing `.end()` to column 0.
 */
component extends="wheels.wheelstest.system.BaseSpec" {

	function beforeAll() {
		variables.testHelper = new cli.lucli.tests.TestHelper();
		variables.tempRoot = testHelper.scaffoldTempProject(expandPath("/"));
		var helpers = new cli.lucli.services.Helpers();
		var templates = new cli.lucli.services.Templates(helpers = helpers, projectRoot = variables.tempRoot, moduleRoot = expandPath("/cli/lucli/"));
		variables.scaffold = new cli.lucli.services.Scaffold(
			codeGenService = new cli.lucli.services.CodeGen(templateService = templates, helpers = helpers, projectRoot = variables.tempRoot),
			helpers = helpers,
			projectRoot = variables.tempRoot,
			moduleRoot = expandPath("/cli/lucli/")
		);
		variables.routesPath = variables.tempRoot & "/config/routes.cfm";
		variables.t = Chr(9);
		variables.nl = Chr(10);
	}

	function afterAll() {
		testHelper.cleanupTempProject(variables.tempRoot);
	}

	function run() {

		describe("Scaffold.updateApiRoutes()", () => {

			it("leaves another generator's marked api block alone and adds its own", () => {
				var authBlock = $authBlock();
				fileWrite(routesPath, $routes(authBlock & t & t & "// CLI-Appends-Here" & nl));
				expect(scaffold.updateApiRoutes("articles")).toBeTrue();
				var content = fileRead(routesPath);
				expect(content).toInclude(authBlock);
				var expected = t & t & '.namespace("api")' & nl
					& t & t & t & '.resources(name="articles", except="new,edit")' & nl
					& t & t & ".end()" & nl
					& t & t & "// CLI-Appends-Here";
				expect(content).toInclude(expected);
			});

			it("joins a plain api namespace with the route indented inside it", () => {
				var plain = t & t & '.namespace("api")' & nl
					& t & t & t & '.post(name="ping", pattern="/ping", to="pings##create")' & nl
					& t & t & ".end()" & nl;
				fileWrite(routesPath, $routes(plain & t & t & "// CLI-Appends-Here" & nl));
				expect(scaffold.updateApiRoutes("widgets")).toBeTrue();
				var expected = t & t & '.namespace("api")' & nl
					& t & t & t & '.post(name="ping", pattern="/ping", to="pings##create")' & nl
					& t & t & t & '.resources(name="widgets", except="new,edit")' & nl
					& t & t & ".end()" & nl;
				expect(fileRead(routesPath)).toInclude(expected);
			});

			it("finds an api namespace only outside marked blocks", () => {
				var marked = $routes($authBlock());
				expect(scaffold.$findApiNamespace(marked)).toBe(0);
				var both = $routes($authBlock() & t & t & ".namespace('api')" & nl & t & t & ".end()" & nl);
				expect(scaffold.$findApiNamespace(both)).toBe(Find(".namespace('api')", both));
			});

		});

	}

	private string function $authBlock() {
		return t & t & "// wheels:generate-auth:routes:begin — generated by `wheels generate auth`" & nl
			& t & t & '.namespace("api")' & nl
			& t & t & t & '.post(name="session", pattern="/session", to="sessions##create")' & nl
			& t & t & ".end()" & nl
			& t & t & "// wheels:generate-auth:routes:end" & nl;
	}

	private string function $routes(required string body) {
		// Chr(60): a literal tag in a string trips Lucee's tag scanner.
		return Chr(60) & "cfscript>" & nl & t & "mapper()" & nl & arguments.body
			& t & t & '.root(to="main##index", method="get")' & nl
			& t & t & ".wildcard()" & nl
			& t & ".end();" & nl & Chr(60) & "/cfscript>" & nl;
	}

}
