name: Full Test Suite

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
